#!/usr/bin/env bash
# =============================================================================
# Day 7 — Coolify PaaS
# VM 由你在 GCP Console 手动创建，此脚本负责安装 Coolify
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../config.sh"
source "${SCRIPT_DIR}/../lib/common.sh"

VM_NAME="lab-d07-coolify"

echo "=================================================================="
echo "  Day 7 — Coolify PaaS"
echo "=================================================================="
echo ""
echo "📋 请在 GCP Console 创建 VM，配置如下："
echo ""
echo "  路径：Compute Engine → VM instances → CREATE INSTANCE"
echo ""
echo "  ┌─ 基础配置 ─────────────────────────────────────────────┐"
echo "  │  名称        : lab-d07-coolify                          │"
echo "  │  区域        : us-central1 / us-central1-b            │"
echo "  │  机器类型    : e2-standard-2（2 vCPU / 8 GB）           │"
echo "  │              ⚠️ 必须用 e2-standard-2，Coolify 内置      │"
echo "  │              Traefik+Postgres+Redis，内存需求高           │"
echo "  └────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ 启动磁盘 ─────────────────────────────────────────────┐"
echo "  │  OS          : Debian GNU/Linux 13 (trixie)           │"
echo "  │  磁盘类型    : Standard persistent disk                 │"
echo "  │  大小        : 30 GB                                    │"
echo "  └────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ Networking → Network tags ────────────────────────────┐"
echo "  │  lab-fw                                                 │"
echo "  └────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ Labels ───────────────────────────────────────────────┐"
echo "  │  owner=lab  purpose=lab  day=d07                        │"
echo "  └────────────────────────────────────────────────────────┘"
echo ""
echo "  ⚠️  不需要 Startup script，Coolify 通过 SSH 安装"
echo ""
echo "💡 体验提示：注意选择机型时 e2-standard-2 和 e2-medium 的差异"
echo "   （内存从 4GB 提升到 8GB，价格约翻倍）"
echo ""
read -rp "✅  VM 显示 Running 后，按 Enter 继续... "

echo ""
print_step 1 "读取 VM 公网 IP"
VM_IP=$(get_vm_external_ip "${VM_NAME}")
echo "  外部 IP：${VM_IP}"

print_step 2 "等待 SSH 就绪"
wait_for_ssh "${VM_NAME}"

print_step 3 "安装 Coolify（官方一键脚本，约 3-5 分钟）"
run_on_vm_sudo "${VM_NAME}" "curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash"

echo ""
echo "=================================================================="
echo "✅  Coolify 安装完成"
echo ""
echo "  VM IP：${VM_IP}"
echo ""
echo "🌐 访问 Coolify（⚠️ 安装后约 1-2 分钟才可访问）："
echo "   http://${VM_IP}:8000"
echo ""
echo "📋 初始化步骤："
echo "   1. 注册管理员账号（首次访问）"
echo "   2. 完成引导向导，选 Localhost"
echo "   3. Projects → New Project → New Resource → Docker Image"
echo "      镜像：traefik/whoami，端口：80"
echo ""
echo "💡 Console 体验提示："
echo "   - 查看 VM 的 CPU/内存监控图（Coolify 启动后资源占用明显）"
echo "   - 对比 Day 3 的 e2-medium：Coolify 这台 8GB 的资源使用率如何？"
echo "   - STOP 这台 VM，再 START，观察 Coolify 服务能否自动恢复"
echo ""
echo "🧹 实验结束后执行："
echo "   bash ${SCRIPT_DIR}/cleanup.sh"
echo "=================================================================="
